runtime: nodejs10
entrypoint: "PRIVATE_KEY=$PRIVATE_KEY DATA=$DATA PORT=$PORT TTL=$TTL node dist/index.js"
env_variables:
  PRIVATE_KEY: $PRIVATE_KEY
  DATA: "src/offchainexample.eth.json"
  PORT: 8080
  TTL: $PRIVATE_KEY
includes:
- secret.yaml
